name: Notificação Módulos

on:
  push:
    paths:
      - 'modulo-*.html'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar teste para Discord
        run: |
          curl -v -X POST \
            -H 'Content-type: application/json' \
            -d '{
              "username": "📚 Escola de Obreiros Bot",
              "content": "🚀 Teste de notificação automática de módulos",
              "embeds": [{
                "title": "📖 APOSTILA SEMANAL DISPONÍVEL",
                "description": "Novo módulo publicado!",
                "color": 2186160,
                "fields": [
                  {
                    "name": "✅ Novo Material Liberado",
                    "value": "Módulo de teste publicado na plataforma",
                    "inline": false
                  },
                  {
                    "name": "📋 Formato",
                    "value": "PDF + HTML",
                    "inline": true
                  },
                  {
                    "name": "📥 Download",
                    "value": "[Acessar Plataforma](https://integracaoon2go.github.io/escola-obreiros-2026/)",
                    "inline": true
                  }
                ]
              }]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_MATERIAIS }}"
